# Generated by Django 5.1.2 on 2024-10-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_table',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('var_no', models.IntegerField(null=True)),
                ('item_code', models.CharField(max_length=100, null=True)),
                ('item_name', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('qut', models.IntegerField(max_length=100, null=True)),
                ('rate', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header_table',
            fields=[
                ('var_no', models.AutoField(primary_key=True, serialize=False)),
                ('ac_name', models.CharField(max_length=100, null=True)),
                ('ac_amount', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('var_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
