# Generated by Django 5.1.2 on 2024-10-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_detail_table_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_table',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
