# Generated by Django 5.1.2 on 2024-11-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_remove_detail_table_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_table',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
