# Generated by Django 5.1.2 on 2024-11-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_detail_table_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flage_field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('button_flag', models.CharField(default=False, max_length=100)),
            ],
        ),
    ]
